### PR TITLE
CKAN Function

### PR DESCRIPTION
**Pull request by w-chase**
Added required files for CKAN compatibility

### CODE REVIEW

**Comment by w-chase** [comment]
It still needs one more step to be available but it's very simple to do,

**Comment by drewcassidy** [comment]
Shabby isn't available on ckan yet so this isn't possible

**Comment by w-chase** [comment]
Because you have bundled shabby into your build, it works. I was able to create and install this mod using ckan locally. It seemed to run correctly.

**Comment by drewcassidy** [comment]
Thats not a solution, if another mod does the same it would cause collisions and installation issues

**Comment by w-chase** [comment]
Very true, well I will cancel my pull request when I get home tonight

**Pull request closed without merging**
